apiVersion: v1
kind: Service
metadata:
  name: datanode-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: datanode
spec:
  ports:
  - name: datanode
    port: {{ .Values.dataNode.service.port }}
    targetPort: datanode
  clusterIP: None
  selector:
    app: datanode 