apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.nameNode.replicaCount }}
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        image: "{{ .Values.nameNode.image.repository }}:{{ .Values.nameNode.image.tag }}"
        imagePullPolicy: {{ .Values.nameNode.image.pullPolicy }}
        ports:
        - containerPort: 9000
          name: hdfs
        - containerPort: 9870
          name: web
        env:
        - name: HADOOP_HOME
          value: /opt/hadoop
        - name: HADOOP_CONF_DIR
          value: /etc/hadoop
        - name: CLUSTER_NAME
          value: {{ .Values.clusterName }}
        - name: HADOOP_HEAPSIZE_MAX
          value: {{ .Values.nameNode.resources.limits.memory | replace "Gi" "000" | replace "Mi" "" | int | sub 500 | toString }}M
        - name: HADOOP_HEAPSIZE_MIN
          value: {{ .Values.nameNode.resources.requests.memory | replace "Gi" "000" | replace "Mi" "" | int | sub 500 | toString }}M
        volumeMounts:
        - name: hdfs-name
          mountPath: /hadoop/dfs/name
        - name: config
          mountPath: /etc/hadoop
        resources:
          {{- toYaml .Values.nameNode.resources | nindent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ .Values.nameNode.configMap.name }}
      {{- if .Values.nameNode.persistence.enabled }}
      - name: hdfs-name
        persistentVolumeClaim:
          claimName: namenode-pvc
      {{- else }}
      - name: hdfs-name
        emptyDir: {}
      {{- end }} 