apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: namenode
  ports:
  - name: hdfs
    port: {{ .Values.nameNode.service.port }}
    targetPort: hdfs
  - name: web
    port: {{ .Values.nameNode.service.webPort }}
    targetPort: web
  type: {{ .Values.nameNode.service.type }} 