apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app: clickhouse
data:
  pre-init.sh: |-
    #!/bin/bash
    
    set -e
    echo "Pre-initializing ClickHouse configuration"
    cat /etc/clickhouse-server/custom-config.xml.template | python3 /preprocessor.py > /etc/clickhouse-server/config.d/custom-config.xml
    echo "Pre-initialization complete"
    set +e
    echo "Starting ClickHouse /entrypoint.sh"
    exec /entrypoint.sh

  preprocessor.py: |-
    import sys
    import json
    import os
    import re

    def main():
        # Read the input from stdin
        data = sys.stdin.read()
        if 'HOSTNAME' not in os.environ:
            raise Exception("HOSTNAME env var is not set")
        server_id = int(os.environ['HOSTNAME'].split('-')[-1].strip())
        out = data.format(server_id=server_id)
        print(out)

    if __name__ == "__main__":
        main()

  custom-config.xml.template: |-
    <clickhouse>
      <path>{{ .Values.clickhouse.persistence.mountPath }}</path>
      <!-- <tmp_path>{{ .Values.clickhouse.persistence.mountPath }}/tmp</tmp_path>
      <user_files_path>{{ .Values.clickhouse.persistence.mountPath }}/user_files</user_files_path>
      <format_schema_path>{{ .Values.clickhouse.persistence.mountPath }}/format_schemas</format_schema_path>-->
      
      <listen_host>0.0.0.0</listen_host>

      <logger>
          <level>information</level>
          <console>1</console>
      </logger>

      <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>{server_id}</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>warning</raft_logs_level>
        </coordination_settings>

        <raft_configuration>
            {{- $replicaCount := int .Values.clickhouse.replicas }}
            {{- range $i := until $replicaCount }}
            <server>
                <id>{{ add $i 1 }}</id>
                <hostname>clickhouse-{{ $i }}</hostname>
                <port>9234</port>
            </server>
            {{- end }}
        </raft_configuration>
      </keeper_server>
      
      <zookeeper>
        {{- $replicaCount := int .Values.clickhouse.replicas}}
        {{- range $i := until $replicaCount }}
        <node>
            <host>clickhouse-{{ $i }}</host>
            <port>9181</port>
        </node>
        {{- end }}
      </zookeeper>

      <remote_servers>
        <{{ .Values.clickhouse.config.clusterName }}>
          {{- $replicaCount := int .Values.clickhouse.replicas }}
          {{- range $i := until $replicaCount }}
          <shard>
              <replica>
                <host>clickhouse-{{ $i }}</host>
                <port>9000</port>
                <user>admin</user>
                <password>admin</password>
              </replica>
          </shard>
          {{- end }}
        </{{ .Values.clickhouse.config.clusterName }}>
      </remote_servers>
    </clickhouse>


