apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clickhouse.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app: clickhouse
spec:
  clusterIP: None
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: tcp
      port: 9000
      targetPort: 9000
    - name: zookeeper
      port: 9181
      targetPort: 9181
    - name: keeper
      port: 9234
      targetPort: 9234
  