apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app: clickhouse
spec:
  serviceName: clickhouse
  replicas: {{ .Values.clickhouse.replicas }}
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
        {{- include "clickhouse.labels" . | nindent 8 }}
    spec:
      containers:
      - name: clickhouse
        image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
        imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.clickhouse.service.httpPort }}
        - name: tcp
          containerPort: {{ .Values.clickhouse.service.tcpPort }}
        resources:
          {{- toYaml .Values.clickhouse.resources | nindent 10 }}
        env:
        - name: CLICKHOUSE_CONFIG
          value: /etc/clickhouse-server/config.xml
        - name: CLICKHOUSE_USER
          value: admin
        - name: CLICKHOUSE_PASSWORD
          value: admin
        volumeMounts:
        {{- if .Values.clickhouse.persistence.enabled }}
        - name: data
          mountPath: {{ .Values.clickhouse.persistence.mountPath }}
        {{- end }}
        - name: pre-init
          mountPath: /pre-init.sh
          subPath: pre-init.sh
          mode: 0755
        - name: preprocessor
          mountPath: /preprocessor.py
          subPath: preprocessor.py
        - name: config
          mountPath: /etc/clickhouse-server/custom-config.xml.template
          subPath: custom-config.xml.template
      volumes:
      - name: config
        configMap:
          name: clickhouse-config
          # items:
          # - key: config.xml
          #   path: config.xml
          # - key: users.xml
          #   path: users.xml
          # - key: config_d_docker_related_config.xml
          #   path: config.d/docker_related_config.xml
  {{- if .Values.clickhouse.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.className }}
      resources:
        requests:
          storage: {{ .Values.storage.size }}
  {{- end }}

