{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grader-chart.fullname" . }}-rabbitmq
  labels:
    {{- include "grader-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "grader-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }} 