{{- if and .Values.rabbitmq.enabled .Values.rabbitmq.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grader-chart.fullname" . }}-rabbitmq
  labels:
    {{- include "grader-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size }}
{{- end }} 