{
 "title": "geowsm",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes{job=\"node-exporter\"}[5s])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(avg_over_time(node_memory_MemFree_bytes{job=\"node-exporter\"}[1m]) + avg_over_time(node_memory_Cached_bytes{job=\"node-exporter\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{job=\"node-exporter\"}[1m]))",
     "legendFormat": "available"
    },
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\"}[1m])",
     "legendFormat": "node_memory_MemTotal_bytes"
    },
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes{job=\"node-exporter\"}[1m])",
     "legendFormat": "node_memory_MemFree_bytes"
    },
    {
     "expr": "avg_over_time(node_memory_Cached_bytes{job=\"node-exporter\"}[1m])",
     "legendFormat": "node_memory_Cached_bytes"
    },
    {
     "expr": " avg_over_time(node_memory_Buffers_bytes{job=\"node-exporter\"}[1m])",
     "legendFormat": "node_memory_Buffers_bytes"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=\"node-exporter\"}[1m]) + avg_over_time(node_memory_Cached_bytes{job=\"node-exporter\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{job=\"node-exporter\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\"}[1m])))"
    }
   ]
  },
  {
   "title": "node cpu average %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": " (1 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[30s])) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "cpu cores average %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": " 100 - (avg by(cpu) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Number of completed tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tasks_count{job=\"python-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "active_users_count{job=\"python-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "geowsm-app CPU usage %",
   "type": "timeseries",
   "description": "geowsm-app container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100 * (\nrate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"geowsm-app\"}[1m])\n    / on(node) group_left()\n  machine_cpu_cores\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "geowsm-app memory usage",
   "type": "timeseries",
   "description": "geowsm-app container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"geowsm-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "geowsm-pg CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "100 * (\nrate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"geowsm-pg\"}[1m])\n    / on(node) group_left()\n  machine_cpu_cores\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "geowsm-pg memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"geowsm-pg\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "geowsm-ch CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "100 * (\nrate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"geowsm-ch\"}[1m])\n    / on(node) group_left()\n  machine_cpu_cores\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "geowsm-ch memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"geowsm-ch\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}