---
apiVersion: v1
kind: Namespace
metadata:
  name: hdfs-3
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: hdfs-3
  labels:
    app: hdfs-namenode
spec:
  type: NodePort
  ports:
  - port: 9000
    name: fs
  - port: 9870
    name: http
    nodePort: 31183
  selector:
    app: hdfs-namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  namespace: hdfs-3
spec:
  serviceName: "hdfs-namenode"
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
        - name: hdfs-namenode
          image: node03.st:5000/hadoop_322_namenode:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "16Gi"
          env:
            - name: CLUSTER_NAME
              value: hdfs-3
            - name: HADOOP_HEAPSIZE_MAX
              value: "16384"
            - name: HADOOP_HEAPSIZE_MIN
              value: "16384"
          ports:
          - containerPort: 9000
            name: fs
          - containerPort: 9870
            name: http
          volumeMounts:
            - name: hdfs-namenode-storage
              mountPath: /hadoop/dfs/name
            - name: config-volume
              mountPath: /etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: config-volume
              mountPath: /etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
          command:
            - "/bin/bash"
            - "-c"
            - "--"
          args :
            - '. ./entrypoint.sh; . ./run.sh'
      nodeSelector:
        kubernetes.io/hostname: node05.st
      restartPolicy: Always
      volumes:
        - name: hdfs-namenode-storage
          hostPath:
            path: /data/hdfs-3-name
            type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: namenode-file-config
            items:
            - key: hdfs-site.xml
              path: hdfs-site.xml
            - key: core-site.xml
              path: core-site.xml

