---
apiVersion: v1
kind: Namespace
metadata:
  name: hdfs-3
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hdfs-datanode
  namespace: hdfs-3
spec:
  selector:
    matchLabels:
      name: hdfs-datanode
  template:
    metadata:
      labels:
        name: hdfs-datanode
    spec:
      containers:
        - name: hdfs-datanode
          image: node03.st:5000/hadoop_322_datanode:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: CLUSTER_NAME
              value: hdfs-3
            - name: JAVA_OPTS
              value: "-Dsun.net.inetaddr.ttl=0"
          securityContext:
            privileged: true
          ports:
            - containerPort: 9866
              name: fs
            - containerPort: 9864
              name: http
              hostPort: 31007
          volumeMounts:
            - name: hdfs-data-storage
              mountPath: /hadoop/dfs/data
            - name: config-volume
              mountPath: /etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: config-volume
              mountPath: /etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
          command:
            - "/bin/bash"
            - "-c"
            - "--"
          args :
            - '. ./entrypoint.sh; . ./run.sh'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: hdfs-datanode-exclude
                  operator: DoesNotExist
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - node06.st
                  - node07.st
                  - node08.st
                  - node09.st
                  - node10.st
                  - node11.st
                  - node12.st
                  - node13.st
                  - node14.st
                  - node15.st
                  - node16.st
                  - node17.st
                  - node18.st
                  - node19.st
                  - node21.st
      restartPolicy: Always
      volumes:
        - name: hdfs-data-storage
          hostPath:
            path: /data/hdfs-3-data
            type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: datanode-file-config
            items:
            - key: hdfs-site.xml
              path: hdfs-site.xml
            - key: core-site.xml
              path: core-site.xml
