---
apiVersion: v1
kind: Service
metadata:
  namespace: clickhouse
  name: clickhouse-nodeport
  labels:
    service: clickhouse-db
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30900
      name: tcp
    - port: 8123
      nodePort: 30812
      name: http
  selector:
    service: clickhouse-db