---
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-clickhouse-0
  labels:
    service: general-clickhouse
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data_1tb/general-clickhouse
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node11.st
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-clickhouse-0
  namespace: clickhouse
  labels:
    service: general-clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
  volumeName: pv-clickhouse-0