---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-0
  labels:
    service: zookeeper
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data_1tb/general-clickhouse-zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - node09.st
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-config
  labels:
    service: zookeeper
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - relatime
  nfs:
    path: /nfs_storage/services/general-clickhouse-zookeeper/conf
    readOnly: true
    server: 10.32.7.103
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: clickhouse
  name: pvc-zookeeper-config
  labels:
    service: zookeeper
spec:
  volumeName: pv-zookeeper-config
  storageClassName: slow
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zookeeper-0
  namespace: clickhouse
  labels:
    service: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: pv-zookeeper-0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: clickhouse
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  serviceName: "zookeeper"
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-zookeeper-config
            readOnly: true
      containers:
        - name: zookeeper
          image: node03.st:5000/zookeeper:3.7.0
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181  # ZK client
            - containerPort: 2888  # Follower
            - containerPort: 3888  # Election
            - containerPort: 8080  # AdminServer
          volumeMounts:
            - mountPath: "/data"          # Zookeeper data dir
              name: pvc
              readOnly: false
              subPath: "data"
            - mountPath: "/conf"          # Zookeeper config dir
              name: config
              readOnly: true
            - mountPath: "/datalog"       # Zookeeper datalog dir
              name: pvc
              readOnly: false
              subPath: "datalog"
            - mountPath: "/log"           # Zookeeper log dir
              name: pvc
              readOnly: false
              subPath: "log"
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-storage
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: clickhouse
  labels:
    service: zookeeper
spec:
  clusterIP: None
  selector:
    service: zookeeper