---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab0-jupyter-cm
  namespace: aal-372475
data:
  jupyter_notebook_config.py: |
    c.NotebookApp.trust_xheaders = True
    c.NotebookApp.quit_button = False
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aal-372475
  name: lab0-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      jupyter: lab0
  template:
    metadata:
      labels:
        jupyter: lab0
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: pvc-shared-aal-372475
            readOnly: true
        - name: nfs-home-storage
          persistentVolumeClaim:
            claimName: pvc-aal-372475
            readOnly: false
        - name: jupyter-config
          configMap:
            name: lab0-jupyter-cm
            items:
              - key: jupyter_notebook_config.py
                path: jupyter_notebook_config.py
      serviceAccountName: spark
      containers:
      - name: jupyter
        image: node03.st:5000/pyspark-hdfs-jupyter:aal-372475
        imagePullPolicy: Always
        ports:
        - containerPort: 8282
        command: [ "start-notebook.sh" ]
        args: [ "--NotebookApp.port=8282", "--NotebookApp.token='Y0h85v0y8w'" ]
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
          - mountPath: "/home/jovyan/shared-data"
            name: shared-storage
            readOnly: true
          - mountPath: "/home/jovyan/nfs-home"
            name: nfs-home-storage
            readOnly: false
          - mountPath: "/home/jovyan/.jupyter/jupyter_notebook_config.py"
            name: jupyter-config
            subPath: jupyter_notebook_config.py
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: lab0-jupyter-service
  namespace: aal-372475
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8282
      protocol: TCP
      name: jupyter
  selector:
    jupyter: lab0
