{{- range .Values.storage.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  labels:
    {{- include "clickhouse.labels" $ | nindent 4 }}
spec:
  capacity:
    storage: {{ .size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy }}
  storageClassName: {{ $.Values.storage.className }}
  local:
    path: {{ .path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .node }}
{{- end }} 