{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
  - name: client
    port: {{ .Values.zookeeper.service.clientPort }}
    targetPort: client
    protocol: TCP
  - name: server
    port: {{ .Values.zookeeper.service.serverPort }}
    targetPort: server
    protocol: TCP
  - name: leader-election
    port: {{ .Values.zookeeper.service.leaderElectionPort }}
    targetPort: leader-election
    protocol: TCP
  selector:
    app: zookeeper
{{- end }} 