import os


DEFAULT_WORKER_CONFIG_PATH = "/worker_config.yaml"

ENV_PREFIX = "GRADER"

ENV_VAR_RUNNER_DB_CONN = f"{ENV_PREFIX}_RUNNER_DB_CONN"
ENV_VAR_RUNNER_DB_CONN_EXTERNAL = f"{ENV_PREFIX}_RUNNER_DB_CONN_EXTERNAL"
ENV_VAR_RUNNER_WORKER_ID = f"{ENV_PREFIX}_RUNNER_WORKER_ID"
ENV_VAR_WORKER_CONFIG_PATH = f"{ENV_PREFIX}_WORKER_CONFIG_PATH"

PG_URL = os.getenv("WMS_POSTGRES_URL", "postgresql+asyncpg://postgres:postgres@localhost:5432/wms")

ENV_VAR_CONFIG = f"{ENV_PREFIX}_CONFIG_PATH"
ENV_VAR_EXECUTION_BACKEND = f"{ENV_PREFIX}_EXECUTION_BACKEND"
ENV_VAR_RESULT_STORAGE_URL = f"{ENV_PREFIX}_RESULT_STORAGE_URL"

ENV_VAR_TASK_ID = f"{ENV_PREFIX}_TASK_ID"
ENV_VAR_JOB_ID = f"{ENV_PREFIX}_JOB_ID"
ENV_VAR_ECHO_DB_QUERY = f"{ENV_PREFIX}_ECHO_DB_QUERY"

ENV_VAR_BATCH_WORKER_TYPE = f"{ENV_PREFIX}_BATCH_WORKER_TYPE"
ENV_VAR_BATCH_WORKER_CONFIG_VOLUME = f"{ENV_PREFIX}_BATCH_WORKER_CONFIG_VOLUME"
ENV_VAR_BATCH_WORKER_REMOVE_CONTAINER_POLICY = f"{ENV_PREFIX}_BATCH_WORKER_REMOVE_CONTAINER_POLICY"
ENV_VAR_WORKER_NETWORK = f"{ENV_PREFIX}_WORKER_NETWORK"
ENV_VAR_DOCKER_BACKEND_PULL_IMAGE_BEFORE_START = f"{ENV_PREFIX}_DOCKER_PULL_IMAGE_BEFORE_START"
ENV_VAR_CELERY_BROKER_URL = "CELERY_BROKER_URL"
ENV_VAR_CELERY_RESULT_BACKEND = "CELERY_RESULT_BACKEND"
