import os


ENV_PREFIX = "GRADER"

ENV_VAR_DB_CONN = f"{ENV_PREFIX}_RUNNER_DB_CONN"

PG_URL = os.getenv("WMS_POSTGRES_URL", "postgresql+asyncpg://postgres:postgres@localhost:5432/wms")

ENV_VAR_CONFIG = f"{ENV_PREFIX}_CONFIG_PATH"
ENV_VAR_EXECUTION_BACKEND = f"{ENV_PREFIX}_EXECUTION_BACKEND"
ENV_VAR_RESULT_STORAGE_URL = f"{ENV_PREFIX}_RESULT_STORAGE_URL"

ENV_VAR_ECHO_DB_QUERY = f"{ENV_PREFIX}_ECHO_DB_QUERY"

ENV_VAR_CELERY_BROKER_URL = "CELERY_BROKER_URL"
ENV_VAR_CELERY_RESULT_BACKEND = "CELERY_RESULT_BACKEND"

