import os


DEFAULT_WORKER_CONFIG_PATH = "/worker_config.yaml"
DEFAULT_JOBS_FOLDER = "/jobs"

ENV_PREFIX = "GRADER"

ENV_VAR_TOKEN = f"{ENV_PREFIX}_TOKEN"
ENV_VAR_ECHO_DB_QUERY = f"{ENV_PREFIX}_ECHO_DB_QUERY"

ENV_VAR_RUNNER_DB_CONN = f"{ENV_PREFIX}_RUNNER_DB_CONN"
ENV_VAR_RUNNER_DB_CONN_EXTERNAL = f"{ENV_PREFIX}_RUNNER_DB_CONN_EXTERNAL"
ENV_VAR_RUNNER_WORKER_ID = f"{ENV_PREFIX}_RUNNER_WORKER_ID"
ENV_VAR_WORKER_CONFIG_PATH = f"{ENV_PREFIX}_WORKER_CONFIG_PATH"
ENV_VAR_LOGGING_LEVEL = f"{ENV_PREFIX}_LOGGING_LEVEL"


TESTS_DOCKER_MODE = os.environ.get("TESTS_DOCKER_MODE", False)
API_HOST = os.environ.get("API_HOST", "geowsm-app")

RABBITMQ_USER = os.environ.get("RABBITMQ_USER", "user")
RABBITMQ_PASSWORD = os.environ.get("RABBITMQ_PASSWORD", "bitnami")
RABBITMQ_PORT = os.environ.get("RABBITMQ_PORT", "5672")
RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST", "geowsm-rabbitmq")

REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", "password")
REDIS_PORT = int(os.environ.get("REDIS_PORT", 6379))
REDIS_HOST = os.environ.get("REDIS_HOST", "geowsm-redis")
CUBE_SLICE_IMAGE_CACHE_TTL_HOURS = int(
    os.environ.get("CUBE_SLICE_IMAGE_CACHE_TTL_HOURS", 24)
)

PG_URL = os.getenv("WMS_POSTGRES_URL", "postgresql+asyncpg://postgres:postgres@localhost:5432/wms")

RN_DATASTORAGE_BASE_URL = os.environ.get(
    "RN_DATASTORAGE_BASE_URL", "http://10.32.0.243:8095/api/rpc"
)
RN_USER_MANAGER_BASE_URL = os.environ.get(
    "RN_USER_MANAGER_BASE_URL", "http://10.32.0.243:8094/api/rpc"
)
VOLUME_BARCHART_BINS = int(os.environ.get("VOLUME_BARCHART_BINS", 100))

JSONRPC_API_ROOT = os.environ.get("JSONRPC_API_ROOT", "/api/rpc")

PROMETHEUS_BASE_URL = os.environ.get(
    "PROMETHEUS_BASE_URL", "http://geowsm-prometheus:9090/api/v1/query"
)

# Точка монтирования дисков, на которых хранятся данные на расчётных узлах
DATA_DISK_MOUNT_POINT = os.environ.get(
    "DATA_DISK_MOUNT_POINT", "/mnt/ess_rn"
)

JWT_KEYS_PATH = os.environ.get("JWT_KEYS_PATH", "/jwt-keys/private.key")

DISABLE_PACKAGES_INCOMPATIBLE_WITH_ARM_ARCH = bool(
    os.environ.get("DISABLE_PACKAGES_INCOMPATIBLE_WITH_ARM_ARCH", False)
)
# Минимальный объем выделенной памяти, при котором будет вызвана очистка памяти (malloc_trim) после выполнения запроса,
# 0 отключает trim по данному условию
ALLOC_MEMORY_MAX_BYTES = int(os.environ.get('ALLOC_MEMORY_MAX_BYTES', 2 * 1024 * 1024 * 1024))

# Определяет во сколько раз выделенный объем памяти должен превышать реально используемую память для вызова malloc_trim,
# 0 отключает trim по данному условию
ALLOC_USED_MEMORY_RATIO = float(os.environ.get('ALLOC_USED_MEMORY_RATIO',  8))

ENV_WMS_CONFIG = "WMS_CONFIG_PATH"
ENV_WMS_EXECUTION_BACKEND = "WMS_EXECUTION_BACKEND"
ENV_WMS_SESSION_STATUS_STORAGE_URL = "WMS_SESSION_STATUS_STORAGE_URL"
ENV_WMS_RESULT_STORAGE_URL = "WMS_RESULT_STORAGE_URL"
ENV_WMS_TUNINGS_PROJECTS_AND_USES_API_URL = "WMS_TUNINGS_PROJECTS_AND_USES_API_URL"
ENV_WMS_HANDLE_TUNINGS_MODE = "WMS_HANDLE_TUNINGS_MODE"

ENV_WMS_CELERY_BROKER_URL_EXTERNAL = "WMS_CELERY_BROKER_URL_EXTERNAL"
ENV_WMS_CELERY_RESULT_BACKEND_EXTERNAL = "WMS_CELERY_RESULT_BACKEND_EXTERNAL"


CM_NAME = 'external-configmap'

# todo: change the prefix
ENV_VAR_TASK_ID = f"{ENV_PREFIX}_TASK_ID"
ENV_VAR_JOB_ID = f"{ENV_PREFIX}_JOB_ID"

# docker or kubernetes
ENV_VAR_INTERACTIVE_WORKER_CONCURRENCY = f"{ENV_PREFIX}_INTERACTIVE_WORKER_CONCURRENCY"

ENV_VAR_BATCH_WORKER_TYPE = f"{ENV_PREFIX}_BATCH_WORKER_TYPE"
ENV_VAR_BATCH_WORKER_CONFIG_VOLUME = f"{ENV_PREFIX}_BATCH_WORKER_CONFIG_VOLUME"
ENV_VAR_BATCH_WORKER_REMOVE_CONTAINER_POLICY = f"{ENV_PREFIX}_BATCH_WORKER_REMOVE_CONTAINER_POLICY"

ENV_VAR_WORKER_NETWORK = f"{ENV_PREFIX}_WORKER_NETWORK"

ENV_VAR_JOBS_FOLDER = f"{ENV_PREFIX}_JOBS_FOLDER"

ENV_VAR_DOCKER_BACKEND_PULL_IMAGE_BEFORE_START = f"{ENV_PREFIX}_DOCKER_PULL_IMAGE_BEFORE_START"

ENV_VAR_CELERY_BROKER_URL = "CELERY_BROKER_URL"
ENV_VAR_CELERY_RESULT_BACKEND = "CELERY_RESULT_BACKEND"
